### PR TITLE
Apply cookiecutter

### PR DESCRIPTION
**Pull request by marcospri**
For: https://github.com/hypothesis/report/issues/2

This applies https://github.com/hypothesis/cookiecutters/tree/main/pyramid-app to the repo and 
made a few small changes afterwards:

- No pyramid
- No devdata
- Make sure that `make docker-run` runs the metabae image.

It does not change the existing `Dockerfile` image.

### CODE REVIEW

**Review by jon-betts — COMMENTED** [review]
I bumped into a couple of things:

 * Running `make docker-run` results in "open .devdata.env no such file or directory."
 * If you run `make template" some files are modified

Other than that "make sure" works... although it's a bit silly right now. Seems like a good platform to start on.

**Comment by seanh** [comment]
> Running make docker-run results in "open .devdata.env no such file or directory."

That's a bug in the cookiecutter, although I don't think there's a GitHub issue for it. There's probably a few more things like this that would naturally get fixed as we roll out the cookiecutter. Surprisingly this is actually the first project to use the "Pyramid app" cookiecutter :)

**Review by seanh — APPROVED** [review]
:+1: Thanks for applying the cookiecutter to this project.

About the changes that running `make template` produces on this branch - some of the conflicts are growing pains with the cookiecutter. The `pyramid-app` cookiecutter actually hasn't been applied to any real projects yet (this is the first!) so there are some small bugs and missing features that need doing in the cookiecutter. Some of the conflicts are things that can be fixed in this repo with the current cookiecutter:

* I would just leave the `factory-boy`, `pyramid-ipython`, `pyramid` and `gunicorn` requirements in the requirements files for now. I know they're not needed but it'll make the cookiecutter apply cleanly and I don't think they do any harm.

  I think we need some changes in the cookiecutters repo before the cookiecutter can apply cleanly to a project like this one or h-periodic that is an app but not a Pyramid app, without adding Pyramid and related requirements to the project. Some discussion of the needed changes [in Slack](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1666775863630609).

  Alternatively you could push a branch to the cookiecutters repo with the changes necessary to make `make template` apply cleanly to this repo. Then use the `checkout` setting in this repo's `cookiecutter.json` to move this repo to the branch of the cookiecutter. We then have to keep the cookiecutters branch up to date with `main` if we want this repo to get new cookiecutter changes from `main`. When we get around to fixing the cookiecutter's `main` branch so that the cookiecutter can apply cleanly to projects like this one, we can then move this project back to `main`.

* Looks like you removed the `make devdata` command? We should put that back: even if this project has no devdata, the cookiecutter's intention is to add a do-nothing `make devdata` command to every project. This is convenient for scripting and documentation because you can always run `make devdata` and it'll never crash in any project, even if it doesn't do anything. Similarly every project is supposed to have `make services` even if it doesn't do anything.

* If you want the title in the `README` to have a capital R then the `name` setting in `cookiecutter.json` should have a capital R. Don't worry: it'll be lowercased when it gets used in lowercase contexts like the directory name etc.

* `make template` ia removing the line `Used for internal purposes only` from `README.md`. Looks like there's a missing feature in the cookiecutter here. You should be able to put that line in `.cookiecutter/includes/README/head.md` instead of editing `README.md` directly. The `pypackage` cookiecutter's `README.md` template [supports this include](https://github.com/hypothesis/cookiecutters/blob/ebfeeba9ffd65d4de6e65c0d858afecf6fa0a082/pypackage/%7B%7B%20cookiecutter.slug%20%7D%7D/README.md?plain=1#L14). But the [`pyramid-app` cookiecutter's `README.md` template](https://github.com/hypothesis/cookiecutters/blob/main/pyramid-app/%7B%7B%20cookiecutter.slug%20%7D%7D/README.md?plain=1) is missing support for this include

* Seems to be some changes to the `docker run` command as well?

**Comment by seanh** [comment]
`make services` is broken for me, at least on my mac. Not sure if it's a macOS problem.

**Pull request merged**
